config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :results
  resources :students
  resources :exams
  resources :terms
  resources :academic_years
  resources :subjects
  resources :classrooms
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :academic_year
  belongs_to :exam
  def stud_name
  	"#{adm_no}: #{first_name} #{last_name}"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:adm_no, :first_name, :last_name, :academic_year_id, :exam_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.haml
= form_for @student do |f|
  - if @student.errors.any?
    #error_explanation
      %h2= "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
      %ul
        - @student.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :adm_no
    = f.number_field :adm_no
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :academic_year
    = f.collection_select :academic_year_id, AcademicYear.order(:year), :id, :year, include_blank: true
    / = f.text_field :academic_year
  .field
    = f.label :exam
    = f.collection_select :exam_id, Exam.order(:name), :id, :name, include_blank: true
    / = f.text_field :exam
  .actions
    = f.submit 'Save'

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
%h1 Listing students

%table
  %thead
    %tr
      %th Adm no
      %th First name
      %th Last name
      %th Academic year
      %th Exam
      %th
      %th
      %th

  %tbody
    - @students.each do |student|
      %tr
        %td= student.adm_no
        %td= student.first_name
        %td= student.last_name
        %td= student.academic_year.year
        %td= student.exam.name
        %td= link_to 'Show', student
        %td= link_to 'Edit', edit_student_path(student)
        %td= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Student', new_student_path

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to 'Back', students_path

app/views/students/show.html.haml
%p#notice= notice

%p
  %b Adm no:
  = @student.adm_no
%p
  %b First name:
  = @student.first_name
%p
  %b Last name:
  = @student.last_name
%p
  %b Academic year:
  = @student.academic_year.year
%p
  %b Exam:
  = @student.exam.name

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', students_path