config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :results
  resources :students
  resources :exams
  resources :terms
  resources :academic_years
  resources :subjects
  resources :classrooms
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :exam
  belongs_to :student
  
  has_many :marks, dependent: :destroy
  accepts_nested_attributes_for :marks
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: %i[ show edit update destroy ]

  # GET /results or /results.json
  def index
    @results = Result.all
  end

  # GET /results/1 or /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
    4.times { @result.marks.build}
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results or /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: "Result was successfully created." }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1 or /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: "Result was successfully updated." }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1 or /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: "Result was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def result_params
      params.require(:result).permit(:exam_id, :student_id, marks_attributes: [:id, :mark, :subject_id])
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.haml
= form_for @result do |f|
  - if @result.errors.any?
    #error_explanation
      %h2= "#{pluralize(@result.errors.count, "error")} prohibited this result from being saved:"
      %ul
        - @result.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :exam
    = f.collection_select :exam_id, Exam.order(:name), :id, :name, include_blank: true
    / = f.text_field :exam
  .field
    = f.label :student
    = f.collection_select :student_id, Student.order(:adm_no), :id, :stud_name, include_blank: true
    / = f.text_field :student

  %hr
  = f.fields_for :marks do |mark|
    .field
      = mark.label :subject
      = mark.collection_select :subject_id, Subject.order(:code), :id, :name, include_blank: true
      / = mark.text_field :subject
    .field
      = mark.label :mark
      = mark.text_field :mark
    %hr 

  .actions
    = f.submit 'Save'

app/views/results/edit.html.haml
%h1 Editing result

= render 'form'

= link_to 'Show', @result
\|
= link_to 'Back', results_path

app/views/results/index.html.haml
%h1 Listing results

%table
  %thead
    %tr
      %th Ac Term
      %th Exam 
      %th Student
      %th.thead English
      %th.thead Swa
      %th.thead Maths
      %th.thead History
      %th
      %th

  %tbody
    - @results.each do |result|
      %tr
        %td= result.exam.term.name
        %td= result.exam.name 
        %td= result.student.stud_name
        - result.marks.each do |mark|
          / %td= mark.subject.name
          %td= mark.mark

        %td= link_to 'Show', result
        %td= link_to 'Edit', edit_result_path(result)
        %td= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Result', new_result_path

app/views/results/new.html.haml
%h1 New result

= render 'form'

= link_to 'Back', results_path

app/views/results/show.html.haml
%p#notice= notice

%p
  %b Exam:
  = @result.exam.name
%p
  %b Student:
  = @result.student.stud_name
%hr

%table
  %thead
    %tr
      %th Subject
      %th Mark

  %tbody
    - @result.marks.each do |mark|
      %tr
        %td= mark.subject.name
        %td= mark.mark


= link_to 'Edit', edit_result_path(@result)
\|
= link_to 'Back', results_path