config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :results
  resources :students
  resources :exams
  resources :terms
  resources :academic_years
  resources :subjects
  resources :classrooms
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:code, :name)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.haml
= form_for @subject do |f|
  - if @subject.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subject.errors.count, "error")} prohibited this subject from being saved:"
      %ul
        - @subject.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :code
    = f.number_field :code
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/subjects/edit.html.haml
%h1 Editing subject

= render 'form'

= link_to 'Show', @subject
\|
= link_to 'Back', subjects_path

app/views/subjects/index.html.haml
%h1 Listing subjects

%table
  %thead
    %tr
      %th Code
      %th Name
      %th
      %th
      %th

  %tbody
    - @subjects.each do |subject|
      %tr
        %td= subject.code
        %td= subject.name
        %td= link_to 'Show', subject
        %td= link_to 'Edit', edit_subject_path(subject)
        %td= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Subject', new_subject_path

app/views/subjects/new.html.haml
%h1 New subject

= render 'form'

= link_to 'Back', subjects_path

app/views/subjects/show.html.haml
%p#notice= notice

%p
  %b Code:
  = @subject.code
%p
  %b Name:
  = @subject.name

= link_to 'Edit', edit_subject_path(@subject)
\|
= link_to 'Back', subjects_path