config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :results
  resources :students
  resources :exams
  resources :terms
  resources :academic_years
  resources :subjects
  resources :classrooms
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/academic_year.rb
class AcademicYear < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :term
  def full_term
  	"#{name}"
  end
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :subject
  belongs_to :result
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :exam
  belongs_to :student
  
  has_many :marks, dependent: :destroy
  accepts_nested_attributes_for :marks
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :academic_year
  belongs_to :exam
  def stud_name
  	"#{adm_no}: #{first_name} #{last_name}"
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :academic_year
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: %i[ show edit update destroy ]

  # GET /exams or /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1 or /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams or /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: "Exam was successfully created." }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1 or /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: "Exam was successfully updated." }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1 or /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: "Exam was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.require(:exam).permit(:name, :term_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: %i[ show edit update destroy ]

  # GET /marks or /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1 or /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks or /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: "Mark was successfully created." }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1 or /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: "Mark was successfully updated." }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1 or /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: "Mark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mark_params
      params.require(:mark).permit(:mark, :subject_id, :result_id)
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: %i[ show edit update destroy ]

  # GET /terms or /terms.json
  def index
    @terms = Term.all
  end

  # GET /terms/1 or /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms or /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: "Term was successfully created." }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1 or /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: "Term was successfully updated." }
        format.json { render :show, status: :ok, location: @term }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1 or /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url, notice: "Term was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def term_params
      params.require(:term).permit(:name, :academic_year_id)
    end
end

app/helpers/academic_years_helper.rb
module AcademicYearsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/exams/_form.html.haml
= form_for @exam do |f|
  - if @exam.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exam.errors.count, "error")} prohibited this exam from being saved:"
      %ul
        - @exam.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :term
    = f.collection_select :term_id, Term.order(:name), :id, :name, include_blank: true
    / = f.text_field :term
  .actions
    = f.submit 'Save'

app/views/exams/edit.html.haml
%h1 Editing exam

= render 'form'

= link_to 'Show', @exam
\|
= link_to 'Back', exams_path

app/views/exams/index.html.haml
%h1 Listing exams

%table
  %thead
    %tr
      %th Name
      %th Term
      %th
      %th
      %th

  %tbody
    - @exams.each do |exam|
      %tr
        %td= exam.name
        %td= exam.term.name
        %td= link_to 'Show', exam
        %td= link_to 'Edit', edit_exam_path(exam)
        %td= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Exam', new_exam_path

app/views/exams/new.html.haml
%h1 New exam

= render 'form'

= link_to 'Back', exams_path

app/views/exams/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @exam.name
%p
  %b Term:
  = @exam.term.name

= link_to 'Edit', edit_exam_path(@exam)
\|
= link_to 'Back', exams_path

app/views/marks/_form.html.haml
= form_for @mark do |f|
  - if @mark.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mark.errors.count, "error")} prohibited this mark from being saved:"
      %ul
        - @mark.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :mark
    = f.text_field :mark
  .field
    = f.label :subject
    = f.text_field :subject
  .field
    = f.label :result
    = f.text_field :result
  .actions
    = f.submit 'Save'

app/views/marks/edit.html.haml
%h1 Editing mark

= render 'form'

= link_to 'Show', @mark
\|
= link_to 'Back', marks_path

app/views/marks/index.html.haml
%h1 Listing marks

%table
  %thead
    %tr
      %th Mark
      %th Subject
      %th Result
      %th
      %th
      %th

  %tbody
    - @marks.each do |mark|
      %tr
        %td= mark.mark
        %td= mark.subject
        %td= mark.result
        %td= link_to 'Show', mark
        %td= link_to 'Edit', edit_mark_path(mark)
        %td= link_to 'Destroy', mark, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Mark', new_mark_path

app/views/marks/new.html.haml
%h1 New mark

= render 'form'

= link_to 'Back', marks_path

app/views/marks/show.html.haml
%p#notice= notice

%p
  %b Mark:
  = @mark.mark
%p
  %b Subject:
  = @mark.subject
%p
  %b Result:
  = @mark.result

= link_to 'Edit', edit_mark_path(@mark)
\|
= link_to 'Back', marks_path

app/views/terms/_form.html.haml
= form_for @term do |f|
  - if @term.errors.any?
    #error_explanation
      %h2= "#{pluralize(@term.errors.count, "error")} prohibited this term from being saved:"
      %ul
        - @term.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :academic_year
    / = f.collection_select :country_id, Country.order(:name), :id, :name, include_blank: true
    = f.collection_select :academic_year_id, AcademicYear.order(:year), :id, :year, include_blank: true
    / = f.text_field :academic_year
  .actions
    = f.submit 'Save'

app/views/terms/edit.html.haml
%h1 Editing term

= render 'form'

= link_to 'Show', @term
\|
= link_to 'Back', terms_path

app/views/terms/index.html.haml
%h1 Listing terms

%table
  %thead
    %tr
      %th Name
      %th Academic year
      %th
      %th
      %th

  %tbody
    - @terms.each do |term|
      %tr
        %td= term.name
        %td= term.academic_year.year
        %td= link_to 'Show', term
        %td= link_to 'Edit', edit_term_path(term)
        %td= link_to 'Destroy', term, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Term', new_term_path

app/views/terms/new.html.haml
%h1 New term

= render 'form'

= link_to 'Back', terms_path

app/views/terms/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @term.name
%p
  %b Academic year:
  = @term.academic_year.year

= link_to 'Edit', edit_term_path(@term)
\|
= link_to 'Back', terms_path